# Reference : https://github.com/mojombo/jekyll/wiki/Configuration

# site info
name      : Felocity
description :
    short : Website of Jakob Heuser
    long  : The personal website of Jakob Heuser

photo:
  title : Her majesty aside
  image : http://jakobo.smugmug.com/People/i-zkdR6G3/0/S/Her%20majesty%20aside_20140514-S.jpg
  url   : http://jakobo.smugmug.com/People/i-zkdR6G3

# permalinks
permalink : /article/:title/

# The production_url is only used when full-domain names are needed such as sitemap.txt
production_url : http://www.felocity.com
url            : http://www.felocity.com

# github defaults
lsi         : false
safe        : true

# overrides maruku
markdown  : redcarpet

# language
lang      : en

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
analytics :
  provider : google
  google :
    tracking_id : 'UA-15075481-1'

# Settings for Disqus
# Set 'shortname' to the disqus shortname
# Set 'developer' to 0 in production, 1 in development to view proper comments
disqus :
  shortname : felocity
  developer : 0
