# Reference : https://github.com/mojombo/jekyll/wiki/Configuration

# site info
name      : Felocity
description :
    short : Website of Jakob Heuser
    long  : The personal website of Jakob Heuser

# permalinks
permalink : /article/:title/

# publish posts with a future date
future    : true

# The production_url is only used when full-domain names are needed such as sitemap.txt
production_url : http://www.felocity.com
url            : http://www.felocity.com

# build config
auto      : true

# github defaults
lsi       : false
pygments  : true
safe      : true

# overrides maruku
markdown  : kramdown
kramdown  :
  entity_output : symbolic

# asset management
# assets :
#   cacheBurst : true
#   stylesheets :
#     - main
#   vendor :
#     scripts :
#       jQuery :
#         version : 1.8.2

# language
lang      : en

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
# analytics :
#   provider : google
#   google :
#     tracking_id : 'UA-1545927-5'

# Settings for Disqus
# Set 'shortname' to the disqus shortname
# Set 'developer' to 0 in production, 1 in development to view proper comments
disqus :
  shortname : injectjs
  developer : 0